# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:41
from __future__ import unicode_literals

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('is_active', models.BooleanField()),
                ('valid_from', models.DateField(blank=True)),
                ('valid_to', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'ip address',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Technical'), (2, 'Administrative'), (3, 'Signee')], default=1, verbose_name='Type')),
                ('name', models.CharField(max_length=75, verbose_name='Name (representative)')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
            options={
                'verbose_name': 'contact',
            },
        ),
        migrations.CreateModel(
            name='SignupQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('name', models.CharField(max_length=75, verbose_name='Name (representative)')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Organization name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('signed_file', models.FileField(blank=True, upload_to=b'/tmp')),
                ('status', models.IntegerField(choices=[(1, 'Request'), (2, 'Generated'), (3, 'Uploaded'), (4, 'Verified'), (5, 'Error')], default=1, verbose_name='Status')),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('date_uploaded', models.DateField(blank=True, null=True)),
                ('date_verified', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'registration',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.SignupQueue'),
        ),
        migrations.AddField(
            model_name='accessright',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.SignupQueue'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('signup', 'type')]),
        )
    ]
