# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('name', models.CharField(max_length=75, verbose_name='Name (representative)')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Organization name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('signed_file', models.FileField(blank=True, upload_to=b'/tmp')),
                ('status', models.IntegerField(choices=[(1, 'Request'), (2, 'Generated'), (3, 'Uploaded'), (4, 'Verified'), (5, 'Error')], default=1, verbose_name='Status')),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('date_uploaded', models.DateField(blank=True, null=True)),
                ('date_verified', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'registration',
            },
        ),
    ]
